### PR TITLE
throw error when dependency is not installed

### LINKED ISSUE #31: Fail build if an external dependency is not installed
Given this example:

```
import { formatDistance, subDays } from "date-fns";

export async function onRequest(event) {
  const timePassed = formatDistance(subDays(new Date(), 3), new Date());
  await event.respondWith(200, `<html>
  <head>
      <title>New content</title>
  </head>
  <body>
    <h1>Content updated: ${timePassed} ago</h1>
  </body></html>`)
}
```

If I don't have `date-fns` installed, the plugin bundles the handle correctly, but it doesn't add the dependency, it prints a message saying that it's considered an external dependency.

We do not allow external dependencies, we need to fail so people understand that they must have all dependencies installed.

### PR DESCRIPTION
**Pull request by shortdiv**
**Which problem is this pull request solving?**
Currently the plugin bundles even when a dependency is treated as an external one. Given that edge handlers requires dependencies to be inlined, the expected outcome is to throw instead of allow the bundle to generate.

**List other issues or pull requests related to this problem**
Fixes #31 

**Describe the solution you've chosen**
Added a configuration in rollup that checks for warning and throws when dependency is not installed.

**Describe alternatives you've considered**

**Checklist**

Please add a `x` inside each checkbox:

- [x] The status checks are successful (continuous integration). Those can be seen below.

### CODE REVIEW

**Review by calavera — APPROVED** [review]
:+1:

File: src/index.js [hunk 1]
```diff
@@ -88,6 +88,11 @@ async function bundleFunctions(file) {
         compact: true,
       }),
     ],
+    onwarn(msg) {
+      if (msg.code == "UNRESOLVED_IMPORT") {
+        throw new Error(`Could not resolve ${msg.source} module. Please install this locally`);
```
Comment (ehmicky) [inline src/index.js:93]: We should use `utils.build.failBuild()` instead, so this error is reported as a user error, not a plugin error.

Comment (shortdiv) [reply src/index.js:93]: Good catch! I'll update this
